columns:
  age: int
  sex: category
  bmi: float
  children: int
  smoker: category
  region: category
  expenses: float

numerical_columns:
  - age
  - bmi
  - children

categorical_columns:
  - sex
  - smoker
  - region

target_column: expenses

domain_value: #Type of values that are accepted in the below column
  sex:
    - male
    - female

  smoker:
    - yes
    - no

  region:
    - southwest
    - southeast
    - northwest
    - northeast
